### PR TITLE
Deprecate AD14 (rebasing of PR #18)

### PR DESCRIPTION
**Pull request by andrew-platt**
Removing AD14 and replacing with AD15.  This PR supercedes #18 (that PR sat for too long and got a bit stale).

The following models still require work to determine the appropriate tau1_const parameter in the ADv15 input file:

- AWT_YFree_WTurb
- AWT_YFix_WSt
- WP_VSP_WTurb_PitchFail
- WP_VSP_WTurb
- SWRT_YFree_VS_WTurb
 

**5MW_ITIBarge_DLL_WTurb_WavesIrr:**
(NOTE: this test was disabled due to numerical instabilities)
Screen Shot 2023-01-30 at 11 27 17 PM
Screen Shot 2023-01-30 at 11 28 36 PM
Some tuning could be done on this case to get a better match.

**AOC_WSt:**
Screen Shot 2023-01-30 at 11 44 27 PM
Screen Shot 2023-01-30 at 11 44 51 PM

**AWT_YFix_WSt:**
using `DBEMT_Mod=2`
(Note: channels changed, so the regression test compare does not work)
Screen Shot 2023-01-31 at 12 07 50 AM

**AWT_YFree_WTurb:**
(Note: channels changed, so the regression test compare does not work)
Screen Shot 2023-01-31 at 12 25 29 AM

**SWRT_YFree_VS_EDC01:**
Screen Shot 2023-01-31 at 12 38 00 AM

**SWRT_YFree_VS_WTurb:**
(NOTE: this test had been disabled due to instabilities and taking forever to run -- shorten it to 20 seconds or leave disabled)
Screen Shot 2023-01-31 at 12 50 14 AM

**UAE_Dnwind_YRamp_WSt:**
(NOTE: this test had been disabled due to instabilities)
Screen Shot 2023-01-31 at 1 10 58 AM

**WP_VSP_WTurb_PitchFail:**
Screen Shot 2023-01-31 at 1 17 58 AM
Screen Shot 2023-01-31 at 1 20 11 AM
Screen Shot 2023-01-31 at 1 20 45 AM

### CODE REVIEW

**Comment by andrew-platt** [comment]
Closes #43

**Review by ebranlard — APPROVED** [review]
Thanks for doing that. I'm all up for the deleting of the summary files. 

My only comment is whether we should keep calling AeroDyn15 AeroDyn15 (in the comments and in the filenames), or if we should just call it AeroDyn.

**Comment by ebranlard** [comment]
Another (annoying) thing I would add, is if we are redoing the baselines, we could prune some output channels and maybe increase the output dt a bit, to potentially reach output binary files of say 200kb. 
For instance: 
-use only only blade number for each output channel name (some kind of rotation between blade 1, 2 or 3). 
- Remove TTDspTwst which is always zero

**Comment by hkross** [comment]
> Another (annoying) thing I would add, is if we are redoing the baselines, we could prune some output channels and maybe increase the output dt a bit, to potentially reach output binary files of say 200kb. For instance: -use only only blade number for each output channel name (some kind of rotation between blade 1, 2 or 3).
> 
>     * Remove TTDspTwst which is always zero

There are a few other ADAMS outputs that are always zero and could be removed as well. @andrew-platt and I discussed this when removing the ADAMS coupling code.

**Comment by bjonkman** [comment]
> Another (annoying) thing I would add, is if we are redoing the baselines, we could prune some output channels and maybe increase the output dt a bit, to potentially reach output binary files of say 200kb. 

Also, if we are redoing baselines.... Since we have updated the way the regression test comparisons work, can we use **packed** binary output instead of the uncompressed binary output that most of the OpenFAST regression tests use? That would also reduce the file size.

**Comment by andrew-platt** [comment]
@bjonkman and @ebranlard, I agree pruning outputs and switching to the packed binary files is a good idea.

**Comment by andrew-platt** [comment]
@ebranlard, I agree on switching the name to just `AeroDyn` in comments and input files.  The current version of AeroDyn is significantly different from the original AeroDyn15 -- if we were really following a numbering system we probably should be on AD18 or so by now.  So calling it simply AeroDyn is much cleaner going forward.  This release is a good time to do that.

**Review by jjonkman — CHANGES_REQUESTED** [review]
Again, thanks for addressing this long-awaited deprecation of AeroDyn v14!

The plots above don't show an instability in the 5MW_ITIBarge_DLL_WTurb_WavesIrr test, so, I'm not sure why this test was removed.  Please clarify.

Can you also clarify what is wrong with the UAE_Dnwind_YRamp_WSt test such that it had to be disabled?  This model uses BEMT (rather than DBEMT) and quasi-steady airfoil aerodynamics (rather than UA), so, is much simpler than other tests.

The comment above mentions the need to tune the `tau1_const` in DBEMT for AWT_YFree_WTurb and SWRT_YFree_VS_WTurb.  It looks like the `tau1_const` was set to 1.0 for these.  `tau1_const` should be derived from Eqn. (45) in the following paper: https://openfast.readthedocs.io/en/main/_downloads/ac04f454598248483d3a339d96dcd4fd/AeroLin_2019-12.pdf.  Has it been?  If not, it shouldn't be too hard to estimate using this Eqn.

The comment above also mentions tuning of the `tau1_const` in DBEMT for AWT_YFix_WSt, but this test uses a time-varying time constant (`DBEMT_Mod` = 2), in which `tau1_const` is not used.

The comment above also mentions tuning of the `tau1_const` in DBEMT for WP_VSP_WTurb_PitchFail, but the new OpenFAST test uses BEMT rather than DBEMT, in which `tau1_const` is not used.  That said, the original AeroDyn v14 model for this test uses GDW, so, was this changed to use BEMT for a reason?

Moreover, the comment above mentions WP_VSP_WTurb, but I don't see that this test was changed (this test already used AeroDyn v15).

The SWRT models are likely unstable because the tail fin aerodynamics are disabled.  Tail fin aerodynamics were added back into OpenFAST in OpenFAST v3.4 (using the tail fin model from FAST v7), so, tail fin aerodynamics should be reactivated in all SWRT tests.  Hopefully the results from OpenFAST will then be similar to the old results from FAST v7.

This PR partially addresses issue [#93](https://github.com/OpenFAST/openfast/issues/178).

**Comment by andrew-platt** [comment]
Closing this PR as #126 now supercedes it.

**Comment by andrew-platt** [comment]
Superceded by #126

**Pull request closed without merging**
