### PR TITLE
Upgrade all ADv14 models to ADv15 (includes DBEMT)

### PR DESCRIPTION
**Pull request by HaymanConsulting**
This pull request updates all r-test models which used AeroDyn version 14 to now use AeroDyn version 15.

The following models still require work to determine the appropriate tau1_const parameter in the ADv15 input file:

AWT_YFree_WTurb
AWT_YFix_WSt
WP_VSP_WTurb_PitchFail
WP_VSP_WTurb
SWRT_YFree_VS_WTurb

Per @jjonkman : 

"I would recommend users use DBEMT_Mod = 1 for most simulations (e.g., turbulence).  I see DBEMT_Mod = 2 only useful for cases where the mean wind speed changes a lot over time, e.g. step-wind cases.  With DBEMT_Mod = 1, I would set tau1_const = 1.1/(1-1.3*min(abar,0.5)) * R/Vbar_hub, which is the standard constant [where] abar is the rotor-averaged axial induction.  Vbar_hub is the time-averaged wind speed at hub height.  To calculate abar, you have to post-process an equivalent simulation using steady wind at the mean wind speed of interest."

All of the revised test cases vary from their baselines (some more than others).  

For example (sample plots only):

WP_VSP_ECD:
BldPitch2

AWT_YFree_WTurb:
NacYawP

AWT_YFix_WSt:
RootFxc2

WP_VSP_WTurb_PitchFail:
RotSpeed

WP_VSP_WTurb:
BldPitch2

AOC_WSt:
LSSGagFys
GenPwr

5MW_ITIBarge_DLL_WTurb_WavesIrr:
BldPitch1
PtfmSway

UAE_Dnwind_YRamp_WSt:
RotAccel

SWRT_YFree_VS_WTurb:
NacYaw

SWRT_YFree_VS_EDC01:
RotSpeed

### CODE REVIEW

**Comment by andrew-platt** [comment]
@ghaymanNREL  what is the status on this?

**Comment by ghaymanNREL** [comment]
@andrew-platt , I have taken this as far as I am able.  Any additional modifications will need to come from the NREL OpenFAST team.

**Comment by andrew-platt** [comment]
@ghaymanNREL thanks!  We'll start a PR on the main OpenFAST branch with these updates (after https://github.com/OpenFAST/openfast/pull/373 and https://github.com/OpenFAST/openfast/pull/447).  Then once fast.FARM is merged (PR not ready yet), we'll do a full deprecation of AD14.

**Comment by jjonkman** [comment]
Why did this PR get closed before it got merged in?  I'd like this PR to get merged in soon.  After talking with @andrew-platt, my understanding is that this PR would be merged in soon.

**Comment by rafmudaf** [comment]
This pull request was automatically closed when I deleted the `reg_test/offshore_linear` branch that it was initially trying to merge into. I've fixed this to merge into `dev`. Good catch @jjonkman.

**Comment by bjonkman** [comment]
FWIW: In https://github.com/OpenFAST/openfast/pull/538 I added a `DBEMTau1` output channel to AeroDyn. You can use this with DBEMT_Mod = 2 to find an appropriate value for tau1 when DBEMT_Mod = 1.

**Comment by andrew-platt** [comment]
Superceded by #87 then #126

**Pull request closed without merging**
